### ISSUE TITLE
Paygate Recurring payment  have no option for notify_url in php exmaple

### ISSUE THREAD

**Issue by arslan7720** [PayGate/PayWeb3#2]
[paygate recurring test.txt](https://github.com/PayGate/PayWeb3/files/53492/paygate.recurring.test.txt)

I am setting up a Recurring payment option on a client site. the payment is for the donation using Paygate "PaySub"(paysubscription) method "https://developer.paygate.co.za/product/13" the code for sending payment requrest work fine. but their code have no clue about the notify_url on which the payment site send a notification to the subscriber site on each recurring due date. How will i keep track of each recurring that happen on its due date. The code for the setting up the recurring payment is mention here.
The sample code provided by the paygate for recurring payment is attached to the text file.

The return url only is for returning from the payment site to subscriber site and its work fine. but the issue is that how i will know the status of each single payment that has been pay through recurring. i means if a recurring payment is set for 1 year then how will i know that on each month the payment is payed.

Thanks in advance.

**Comment by BazzaTheTwit** [comment]
Hi

Our PaySubs product currently doesn't offer transaction processing results via a notify URL.
If a transaction has been processed successfully, then an email is sent out, but no notifications are sent for declines.
If you want to see the results for all PaySubs transactions, including declines, then you would log in to the PayGate Back Office.

If you need any further information, etc, please feel free to contact our support team on support@paygate.co.za

Kind Regards
Barry
